auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("index", views.index, name="index"),
    path("", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("cards", views.cards_view, name="cards"),
    path("add", views.add, name="add"),
    path("add_comment", views.add_comment, name="add_comment"),
    path("listing_details", views.listing_details_view, name="listing_details"),
    path("watchlist", views.watchlist_view, name="watchlist"),
    path("category_list", views.category_list, name="category_list"),
    path("category_list/<str:category>", views.category_list_redirect, name="category_list_redirect"),
    path("add_to_watchlist", views.add_to_watchlist, name="add_to_watchlist"),
    path("place_bid", views.place_bid, name="place_bid"),
    path("end_listing", views.end_listing, name="end_listing"),
    path("auctions_history", views.auctions_history, name="auctions_history"),
    path("delete_item_watchlist", views.delete_item_watchlist, name="delete_item_watchlist")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static, settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    def __str__(self):
        return f"{self.first_name}"



class Item(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="item_list")
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=256, blank=True)
    img_url = models.CharField(max_length=256, blank=True)
    starting_bid = models.DecimalField(decimal_places=2, max_digits=8)
    category = models.CharField(max_length=24, default='No Category')
    status = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.title}, {self.description}"

class ItemCategory(models.Model):
    name = models.CharField(max_length=24, blank=False)
    item = models.ForeignKey(Item, blank=True, on_delete=models.CASCADE, related_name="category_list")
    def __str__(self):
        return f"{self.name}"

class Bid(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_bids")
    amount = models.DecimalField(decimal_places=2, max_digits=8)
    items = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="user_bid_items", blank=True)
    def __str__(self):
        return f"{self.amount}"
    
class ItemComment(models.Model):
    text = models.TextField(max_length=512, blank=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="comments_list")
    author = models.ForeignKey(User, on_delete=models.CASCADE)

class Watchlist(models.Model):
    items = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='watchlist_list')

    def __str__(self):
        return f"{self.items}, {self.user}"

class Category(models.Model):
    name = models.CharField(max_length=24, blank=False)
    items = models.ManyToManyField(Item, blank=True, related_name="categories")

    def __str__(self):
        return f"{self.name}"

class AuctionHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="history_user")
    items = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="items_auction_history")

    def __str__(self):
        return f"{self.user.first_name}, {self.items}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
import logging
from django.db import models

from .models import User, Bid, Item, ItemComment, Watchlist, ItemCategory, AuctionHistory
from .utils import utility
import json 
from django.core import serializers
from django.contrib.auth.decorators import login_required

logger = logging.getLogger('mylogger')
#Define forms based on models


class ItemForm(forms.ModelForm):
    class Meta:
        category_choices = [
            ('clothing', 'Clothing'),
            ('toys', 'Toys'),
            ('electronics', 'Electronics'),
            ('art','Art')
        ]
        model = Item
        fields = ['title', 'description', 'img_url', 'starting_bid', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'item_title',
                                            'placeholder': 'Item Title'}),
            'description': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'item_description',
                                            'placeholder': 'Item Description'}),
            'img_url': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'item_img_url',
                                            'placeholder': 'Image Url'}),
            'starting_bid': forms.NumberInput(attrs={'class': 'form-control',
                                            'id': 'item_starting_bid',
                                            'placeholder': 'Initial Bid'}),   
            'category': forms.Select(choices=category_choices)                                       
        }

class Comment(models.Model):
    comment = models.TextField(max_length=256)

class CommentForm(forms.Form):
    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={
                 'class':"form-control",
                 'id':"textAreaComment",
                 'rows':"2", 'placeholder':"Type a comment"
            })
        }

def index(request):
    #Here in the index page we want to display all active auction listings.
    items = utility.get_items()
    distinct_users = utility.get_users_with_items()
    json_data = serializers.serialize("json", items)
    json_users = json.dumps(distinct_users)
    message=""
    if request.method == 'POST':        
        listing_title = str(request.POST.get("listing_title", False))
        item_ = Item.objects.filter(title=listing_title).get()
        user_ = User.objects.filter(username=request.user.username).get()
        #Search for item in watchlist
        search_item = Watchlist.objects.filter(items=item_, user=user_)
        if len(search_item)==0:
            message="Item added to watchlist"
            Watchlist(items=item_, user=user_).save()
        else:
            message="Item Has already been added to watchlist"
    context = {
        "json" : json_data,
        "users": json_users
    }
    
    if items != None:
        items_with_bids =  Item.objects.filter(user_bid_items__items__isnull=False).distinct()
        bids = []
        for item in items:
            if item in items_with_bids:
                bids.append(Bid.objects.filter(items=item).order_by('amount').last().amount)
            else:
                bids.append(item.starting_bid)
        logger.info(bids)
        items_bids = list(zip(items,bids))
        return render(request, "auctions/index.html",{
            "items":items,
            "items_bids":items_bids,
            "json":json_data,
            "json_users": json_users,
            "commentForm": CommentForm(),
            "message":message
        })
    else:
        logger.info("index get")
        return render(request, "auctions/index.html", {
            "items":items,
        })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        commentForm = CommentForm(request.POST)
        # if commentForm.is_valid():
            #logger.infor(commentForm)

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })
        username = request.POST["username"]
        email = request.POST["email"]
        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

def add(request):
    if request.method == 'GET':
        logger.info("Get add")
        return render(request, "auctions/add.html", {
            "new_form": ItemForm()
        })
    else:
        add_item_form = ItemForm(request.POST)
        if add_item_form.is_valid():
            item_title = add_item_form['title'].value()
            item_desc = add_item_form['description'].value()
            item_img_url = add_item_form['img_url'].value()
            item_str_bid = add_item_form['starting_bid'].value()
            item_cat = add_item_form['category'].value()
            
            #Register a new Item to the db
            new_item = Item(user=request.user, 
                            title=item_title,
                            description=item_desc,
                            img_url=item_img_url,
                            starting_bid=item_str_bid,
                            category=item_cat)
            if new_item != None:
                new_item.save()
                message = "Item successfully added to the db"

                #If the item was added successfully, then create a category with that item after making
                #sure it has not already been added.
                # Category.objects.filter(item=new_item)
                item_category = ItemCategory(name=item_cat, item=new_item)
                item_category.save()

            else:
                message = "Failure while saving to the db"
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/add.html", {
            "new_form": ItemForm(),
            "message": "Invalid Data"
            })

def cards_view(request):
    user = User.objects.filter(username=request.user.username).first()
    # bid = Bid.objects.get(user=user)
    item = Item.objects.filter(user=user)[1]
    description = str(item.description)[0:40] + ".."
    return render(request, "auctions/cards.html", {
        "user":user,
        "item":item,
        "description": description
    })

def listing_details_view(request):
    #Get the listing's title to show on this page
    if request.method == 'POST':        
        listing_title = str(request.POST.get("listing_title", False))
        if (str(request.GET.get("message_bid"))):
            message_bid = str(request.GET.get("message_bid"))
        else:
            message_bid="Couldn't place the bid."
        #Get item object matching this string
        item_ = Item.objects.filter(title=listing_title).get()
        owner = item_.user
        #Comments
        comments = item_.comments_list.all()
        #Search for bids
        search_bid = Bid.objects.filter(items=item_)
        own_this_item = False
        if (item_.user.username == request.user.username):
            own_this_item = True
        if len(search_bid)==0 and message_bid!="Couldn't place the bid.":
            return render(request, "auctions/listing_details.html",{
            "item":item_,
            "owner": owner,
            "comments":comments,
            "last_bid":Bid.objects.filter(items=item_).order_by('amount').last(),
            "privilege": own_this_item
            # "bid": bid
        })
        else:
            return render(request, "auctions/listing_details.html",{
            "item":item_,
            "owner": owner,
            "comments":comments,
            "last_bid":Bid.objects.filter(items=item_).order_by('amount').last(),
            "privilege": own_this_item
            # "bid": bid
        })
        

        
    else:
        # logger.info("Listing Details Get")
        listing_title = str(request.GET.get("listing_title", False))
        
        # logger.info("item name" + listing_title)
        item_ = Item.objects.filter(title=listing_title).get()
        owner = item_.user
        comments = item_.comments_list.all()
        if (str(request.GET.get("message_bid"))):
            message_bid = str(request.GET.get("message_bid"))
        else:
            message_bid="Couldn't place the bid."

auctions/templates/auctions/b.html
<head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<style>
 footer .main-footer{  padding: 20px 0;  background: #252525;}
footer ul{  padding-left: 0;  list-style: none;}

/* Copy Right Footer */
.footer-copyright { background: #222; padding: 5px 0;}
.footer-copyright .logo {    display: inherit;}
.footer-copyright nav {    float: right;    margin-top: 5px;}
.footer-copyright nav ul {  list-style: none; margin: 0;  padding: 0;}
.footer-copyright nav ul li { border-left: 1px solid #505050; display: inline-block;  line-height: 12px;  margin: 0;  padding: 0 8px;}
.footer-copyright nav ul li a{  color: #969696;}
.footer-copyright nav ul li:first-child { border: medium none;  padding-left: 0;}
.footer-copyright p { color: #969696; margin: 2px 0 0;}

/* Footer Top */
.footer-top{  background: #252525;  padding-bottom: 30px; margin-bottom: 30px;  border-bottom: 3px solid #222;}

/* Footer transparent */
footer.transparent .footer-top, footer.transparent .main-footer{  background: transparent;}
footer.transparent .footer-copyright{ background: none repeat scroll 0 0 rgba(0, 0, 0, 0.3) ;}

/* Footer light */
footer.light .footer-top{ background: #f9f9f9;}
footer.light .main-footer{  background: #f9f9f9;}
footer.light .footer-copyright{ background: none repeat scroll 0 0 rgba(255, 255, 255, 0.3) ;}

/* Footer 4 */
.footer- .logo {    display: inline-block;}

/*====================
  Widgets
====================== */
.widget{  padding: 20px;  margin-bottom: 40px;}
.widget.widget-last{  margin-bottom: 0px;}
.widget.no-box{ padding: 0; background-color: transparent;  margin-bottom: 40px;
  box-shadow: none; -webkit-box-shadow: none; -moz-box-shadow: none; -ms-box-shadow: none; -o-box-shadow: none;}
.widget.subscribe p{  margin-bottom: 18px;}
.widget li a{ color: #ff8d1e;}
.widget li a:hover{ color: #4b92dc;}
.widget-title {margin-bottom: 20px;}
.widget-title span {background: #839FAD none repeat scroll 0 0;display: block; height: 1px;margin-top: 25px;position: relative;width: 20%;}
.widget-title span::after {background: inherit;content: "";height: inherit;    position: absolute;top: -4px;width: 50%;}
.widget-title.text-center span,.widget-title.text-center span::after {margin-left: auto;margin-right:auto;left: 0;right: 0;}
.widget .badge{ float: right; background: #7f7f7f;}

.typo-light h1,
.typo-light h2,
.typo-light h3,
.typo-light h4,
.typo-light h5,
.typo-light h6,
.typo-light p,
.typo-light div,
.typo-light span,
.typo-light small{  color: #fff;}

ul.social-footer2 { margin: 0;padding: 0; width: auto;}
ul.social-footer2 li {display: inline-block;padding: 0;}
ul.social-footer2 li a:hover {background-color:#ff8d1e;}
ul.social-footer2 li a {display: block; height:30px;width: 30px;text-align: center;}
.btn{background-color: #ff8d1e; color:#fff;}
.btn:hover, .btn:focus, .btn.active {background: #4b92dc;color: #fff;
-webkit-box-shadow: 0 15px 30px rgba(0, 0, 0, 0.1);
-moz-box-shadow: 0 15px 30px rgba(0, 0, 0, 0.1);
-ms-box-shadow: 0 15px 30px rgba(0, 0, 0, 0.1);
-o-box-shadow: 0 15px 30px rgba(0, 0, 0, 0.1);
box-shadow: 0 15px 30px rgba(0, 0, 0, 0.1);
-webkit-transition: all 250ms ease-in-out 0s;
-moz-transition: all 250ms ease-in-out 0s;
-ms-transition: all 250ms ease-in-out 0s;
-o-transition: all 250ms ease-in-out 0s;
transition: all 250ms ease-in-out 0s;

}
</style>
</head>
<!-- Please Subscribe My Youtube Channel
https://www.youtube.com/channel/UCQM5ye1xR4vJgtga0ryud2Q/
-->
<footer id="footer" class="footer-1">
<div class="main-footer widgets-dark typo-light">
<div class="container">
<div class="row">

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget subscribe no-box">
<h5 class="widget-title">Best Value<span></span></h5>
<p>An Best Value gives best possible transaction between sellers (the auctioneers) and bidders (suppliers in business to business scenarios) that takes place on an electronic marketplace. </p>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget no-box">
<h5 class="widget-title">Quick Links<span></span></h5>
<ul class="thumbnail-widget">
<li>
<div class="thumb-content"><a href="{% url 'auctions:index' %}">Active Listings</a></div>
</li>
<li>
<div class="thumb-content"><a href="{% url 'auctions:category_list' %}.">Category</a></div>
</li>
<li>
<div class="thumb-content"><a href="{% url 'auctions:login' %}.">Login</a></div>
</li>

</ul>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget no-box">
<h5 class="widget-title">Get Started<span></span></h5>
<a class="btn" href="{% url 'auctions:register' %}" target="_blank">Register Now</a>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">

<div class="widget no-box">


</div>
</div>

</div>
</div>
</div>

<div class="footer-copyright">
<div class="container">
<div class="row">
<div class="col-md-12 text-center">

</div>
</div>
</div>
</div>
</footer>

auctions/templates/auctions/layout.html
{% load static %}
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href=""><img src="{% static 'images\4.jpg' %}" style="
    HEIGHT: 40;
"><i> BEST VALUE</i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings
                <span class="sr-only">(current)</span>
              </a>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'auctions:category_list' %}">Categories</a>
            </li>
        {% if user.is_authenticated %}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'auctions:add' %}">Add Item</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'auctions:auctions_history' %}">Auctions History</a>
                </li>
                <li class = "nav-item "><a class="nav-link"> Hello, {{user.username}}</a></li>

            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}

      </ul>
    </div>
  </div>
</nav>
{% block body %}
{% endblock %}

auctions/templates/auctions/listing_details.html
{% extends "auctions/layout.html"  %}
{% load static %}

{% block body %}

<div class="container-fluid ">
    <div class="row justify-content-md-center">
        <div class="col-lg-10 ">
            <div class="card" >
                <img class="card-img-top" height="600px" src="{{item.img_url}}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{item.title}}</h5>
                  <h6 class="card-subtitle mb-2 text-muted">{{owner.username}}</h6>
                 <div style="height:60px; overflow: auto;">
                    <p class="card-text">{{item.description}}.</p>
                 </div>
                 <div>
                   <form method="POST" action="{% url 'auctions:place_bid' %}">
                     {% csrf_token %}
                     {% if item.status %}
                      <input name="new_bid" placeholder="Bid">
                      <input hidden name="listing_title" value="{{item.title}}" placeholder="">
                      <button href="#" id="myBtn" class="btn btn-primary">Place Bid</button>
                     {% endif %}

                   </form>
                 </div>
                  
                  <div style="flex-direction: row; " class="flexbox-container">
                    <label style="font-size: 20px; font-weight: bold; padding-right: 10px;">Bid</label>
                    {% if last_bid %}
                    <label style="font-size: 35px; ">${{last_bid}}</label>  
                    {% else %}
                    <label style="font-size: 35px; ">${{item.starting_bid}}</label>
                    {% endif %}
                  </div>
                  <div  style="flex-flow: row wrap; " class="flexbox-container">
                    <div class="row">
                      <label style="padding-left: 15px; font-size: 20px; font-weight: bold; ">Status</label>
                      {% if item.status %}
                      <div style="width: 20px; height: 20px; border-radius: 50%; border: 1px solid; background-color:green; opacity: 0.4; margin-top: 5px; margin-left: 10px;"></div>
                      {% else %}
                      <div style="width: 20px; height: 20px; border-radius: 50%; border: 1px solid; background-color:red; opacity: 0.4;"></div>
                      {% endif %}
                    </div>
                    {% if privilege %}
                    <form action="{% url 'auctions:end_listing' %}" method="POST">
                      {%csrf_token%}
                      <input hidden name="listing_title" value="{{item.title}}">
                     <button  type="submit" class="btn btn-warning">Time up</button>
                    </form>
                    {% endif %}
                    
                    <!-- {% if item.status %} -->
                    
                     <!-- {% endif %} -->
                  </div>
                  {% if message_bid %}
                    <p style="font-weight: bold; color: green;">{{message_bid}}</p>
                    {%else%}
                  {%endif%}
                </div>

                
                <div class="modal-body">
                  <h5>Comments</h5>

                  {% for comment in comments %}
                    
                    <div class="media-list">
                      <li class="media">
                          <a class="pull-left" href="#">
                             <img class="media-object rounded-circle" height="150px" src="{% static 'auctions/media/alejo_cat.jpeg'%}" alt="profile">
                          </a>
                          <div style="background-color: #E2E2E2; " class="media-body">
                              <div style="padding: 20px; " class="well well-lg">
                                  <h4 class="media-heading text-uppercase reviews">{{comment.author.username}}</h4>
                                  <ul class="media-date text-uppercase reviews ">
                                     <li>22</li>
                                     <li>09</li>
                                     <li>2014</li>
                                  </ul>
                                  <p class="media-comment">
                                     {{comment.text}}
                                  </p>
                              </div>
                          </div>
                      </li> 
                    </div>
                    {% empty %}
                      <h6>No comment has been added yet :C</h6>
                {% endfor %}
                </div> 

                 <form method="POST" action="{% url 'auctions:add_comment' %}">
                   {% csrf_token%}
                  <div class="form-group" style="padding-top: 5px;">
                    <label for="commentText">New comment</label>
                    <input hidden type="text" value="{{item.title}}" name="listing_title">
                    <input hidden type="text" value="{{owner.username}}" name="owner">
                    <textarea class="form-control" name="commentText" id="commentText" rows="3"></textarea>
                    <div style="text-align: right ;" >
                      <button class="btn btn-secondary">Add Comment</button>
                   </div>
                  </div> 
                 </form>                                                
                </div>
            </div>        
        </div>
    </div>
  </div> 

  <!-- <div class="container-fluid">
    <div class="row justify-content-md-center">
      <div class="col-lg-10">
        <div class="card">
          <p>
            Hi
          </p>
        </div>
      </div>
    </div>
  </div> -->

{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}
{% load static %}
{% block body %}
<html>
<head>
	{% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>@import url('https://fonts.googleapis.com/css?family=Numans');

.auc{
background-image: url("/static/images/3.jpg");
background-size: cover;
background-repeat: no-repeat;
height: 100%;

}

.container{
height: 100%;
align-content: center;
font-family: 'Numans', sans-serif;
}

.card{
height: 370px;
margin-top: auto;
margin-bottom: auto;
width: 400px;
background-color: rgba(0,0,0,0.5) !important;
}

.social_icon span{
font-size: 60px;
margin-left: 10px;
color: #FFC312;
}

.social_icon span:hover{
color: white;
cursor: pointer;
}

.card-header h3{
color: white;
}

.social_icon{
position: absolute;
right: 20px;
top: -45px;
}

.input-group-prepend span{
width: 50px;
background-color: #FFC312;
color: black;
border:0 !important;
}

input:focus{
outline: 0 0 0 0  !important;
box-shadow: 0 0 0 0 !important;

}

.remember{
color: white;
}

.remember input
{
width: 20px;
height: 20px;
margin-left: 15px;
margin-right: 5px;
}

.login_btn{
color: black;
background-color: #FFC312;
width: 100px;
}

.login_btn:hover{
color: black;
background-color: white;
}

.links{
color: white;
}

.links a{
margin-left: 4px;
}

</style>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->

	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<br>
<br>
<br>
<body class="auc">
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
            </div>
			<div class="card-body">
				<form action="{% url 'auctions:login' %}" method="post">
					{% csrf_token %}
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" name="username" class="form-control" placeholder="username">
                    </div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>

						<input type="password" name="password" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="submit" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="{% url 'auctions:register' %}">Sign Up</a>
				</div>

			</div>
		</div>
	</div>
</div>
</body>
</html>
{% endblock %}